apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: todohub
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: todohub
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
