apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: todohub
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: todohub
data:
  NEXT_PUBLIC_API_URL: "http://backend:8000"
