apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: todohub
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: todohub
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
      nodePort: 30000
