apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todohub-backend.fullname" . }}-secrets
  labels:
    {{- include "todohub-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
